apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - name: clear-config
        image: busybox
        command: ["sh", "-c", "rm -f /var/www/html/.htaccess; find /var/www/html -maxdepth 1 -type f -not -path '/var/www/html/wp-content/*' -not -name 'wp-config.php' -delete; find /var/www/html -maxdepth 1 -type d -not -name 'wp-content' -not -path '/var/www/html' -exec rm -rf {} \\;"]
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html/wp-content
      containers:
      - name: wordpress
        image: ar2910/wordpress-custom:latest
        env:
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_HOST
          value: mysql-svc:3306
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html/wp-content
        readinessProbe:
          httpGet:
            path: /wp-login.php
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /wp-login.php
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-shared-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-shared-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

